# At develpment, don't copy the files
# which cointain cluster configuration
FROM rabbitmq:3.7-management-alpine as development

FROM rabbitmq:3.7-management-alpine
COPY rabbitmq.conf /etc/rabbitmq/rabbitmq.conf
COPY enabled_plugins /etc/rabbitmq/enabled_plugins
